# XE CPE Stats

[[processors.template]]
order = 1
  namepass = ["xe_cpu_stats"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}'

[[processors.template]]
order = 1
  namepass = ["xe_cpu_stats"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}'


[[processors.template]]
order = 2
  namepass = ["xe_cpu_stats*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-cpu-ak'

[[processors.template]]
order = 3
  namepass = ["xe_cpu_stats*"]
  tag = "direction"
  template = '-1'

[[processors.tag_limit]]
order = 4
  namepass = ["xe_cpu_stats*"]
  fieldinclude = [
        "five_minutes",
        "five_seconds",
        "five_seconds_intr",
        "one_minute"
  ]

  ## Maximum number of tags to preserve
  limit = 4

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType", "direction"]
