# XE Memory Stats

[[processors.template]]
order = 1
  namepass = ["xe_memory_stats"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_{{ .Tag "name" }}'

[[processors.template]]
order = 1
  namepass = ["xe_memory_stats"]
  tag = "sessionName"
   template = '{{ .Tag "source" }}_{{ .Tag "name" }}'


[[processors.template]]
order = 2
  namepass = ["xe_memory_stats*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-memory'

[[processors.template]]
order = 3
  namepass = ["xe_memory_stats*"]
  tag = "direction"
  template = '-1'

[[processors.tag_limit]]
order = 4
  namepass = ["xe_memory_stats*"]
  fieldinclude = [
        "free_memory",
        "highest_usage",
        "lowest_usage",
        "total_memory",
        "used_memory"
  ]

  ## Maximum number of tags to preserve
  limit = 4

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType", "direction"]
