[[processors.template]]
namepass = ["policy_in_stats*", "policy_out_stats*"]
tag = "sessionName"
template = '{{ .Tag "source" }}_{{ .Tag "interface_name" }}_{{if .Tag "class_stats/child_policy/policy_name"}}{{ .Tag "class_stats/child_policy/policy_name" }}_{{ .Tag "class_stats/child_policy/class_stats/class_name" }}{{else}}{{ .Tag "service_policy_name" }}_{{ .Tag "class_stats/class_name" }}{{end}}'

[[processors.template]]
namepass = ["policy_in_stats*", "policy_out_stats*"]
tag = "sessionId"
template = '{{ .Tag "source" }}_{{ .Tag "interface_name" }}_{{if .Tag "class_stats/child_policy/policy_name"}}{{ .Tag "class_stats/child_policy/policy_name" }}_{{ .Tag "class_stats/child_policy/class_stats/class_name" }}{{else}}{{ .Tag "service_policy_name" }}_{{ .Tag "class_stats/class_name" }}{{end}}'

[[processors.template]]
namepass = ["policy_in_stats*", "policy_out_stats*"]
tag = "objectType"
template = 'cisco-telemetry-xr-policy'

[[processors.template]]
namepass = ["policy_in_stats*", "policy_out_stats*"]
tag = "direction"
template = '-1'

[[processors.tag_limit]]
  namepass = ["policy_in_stats*", "policy_out_stats*"]
  fieldinclude = [
        "class_stats/police_stats_array/conform_rate",
        "class_stats/child_policy/class_stats/police_stats_array/conform_rate",
        "class_stats/police_stats_array/exceed_rate",
        "class_stats/child_policy/class_stats/police_stats_array/exceed_rate",
        "class_stats/general_stats/total_drop_rate",
        "class_stats/child_policy/class_stats/general_stats/total_drop_rate",
        "class_stats/general_stats/total_transmit_rate",
        "class_stats/child_policy/class_stats/general_stats/total_transmit_rate",
        "class_stats/queue_stats_array/conform_rate",
        "class_stats/child_policy/class_stats/queue_stats_array/conform_rate",
        "class_stats/child_policy/class_stats/queue_stats_array/exceed_rate",
        "class_stats/general_stats/pre_policy_matched_packets",
        "class_stats/child_policy/class_stats/general_stats/pre_policy_matched_packets",
        "class_stats/general_stats/pre_policy_matched_bytes",
        "class_stats/child_policy/class_stats/general_stats/pre_policy_matched_bytes",
        "class_stats/general_stats/match_data_rate",
        "class_stats/child_policy/class_stats/general_stats/match_data_rate",
        "class_stats/general_stats/transmit_packets",
        "class_stats/child_policy/class_stats/general_stats/transmit_packets",
        "class_stats/general_stats/transmit_bytes",
        "class_stats/child_policy/class_stats/general_stats/transmit_bytes",
        "class_stats/general_stats/total_drop_packets",
        "class_stats/child_policy/class_stats/general_stats/total_drop_packets",
        "class_stats/general_stats/total_drop_bytes",
        "class_stats/child_policy/class_stats/general_stats/total_drop_bytes"
  ]
  ## Maximum number of tags to preserve
  limit = 4

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType","direction"]
