[agent]
  interval = "5s"
  round_interval = false
  flush_interval = "5s"
  omit_hostname = true

[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address = ":57000"
  max_msg_size = 104857600

  [inputs.cisco_telemetry_mdt.aliases]
    xe_cpu_stats = "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization"
    xe_memory_stats = "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic"
    xe_if_stats = "Cisco-IOS-XE-interfaces-oper:interfaces/interface"
    xe_bgp_neighbors = "Cisco-IOS-XE-bgp-oper:bgp-state-data/neighbors/neighbor"
    xe_environment_sensor = "Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor"

[[processors.starlark]]
  order = 1
  namepass = ["xe_if_stats*"]
  source = '''
def apply(metric):
  metric.fields["statistics/in_octets_rate"] = metric.fields.get("statistics/in_octets")
  metric.fields["statistics/out_octets_rate"] = metric.fields.get("statistics/out_octets")
  metric.fields["statistics/out_octets_64_rate"] = metric.fields.get("statistics/out_octets_64")
  return metric
'''

[[processors.starlark]]
  order = 1
  namepass = ["xe_bgp_neighbors*"]
  source = '''
def tag_from_tag(metric, source, target):
  value = metric.tags.get(source)
  if value != None:
    metric.tags[target] = str(value)

def tag_from_field(metric, source, target):
  value = metric.fields.get(source)
  if value != None:
    metric.tags[target] = str(value)

def apply(metric):
  tag_from_tag(metric, "afi_safi", "bgpAfiSafi")
  tag_from_tag(metric, "vrf_name", "bgpVrfName")
  tag_from_tag(metric, "neighbor_id", "bgpNeighborId")
  tag_from_field(metric, "as", "bgpNeighborAs")
  tag_from_field(metric, "link", "bgpLink")
  tag_from_field(metric, "description", "bgpDescription")
  tag_from_field(metric, "session_state", "bgpSessionState")
  tag_from_field(metric, "connection/state", "bgpConnectionState")
  tag_from_field(metric, "connection/reset_reason", "bgpResetReason")
  tag_from_field(metric, "transport/local_host", "bgpLocalHost")
  tag_from_field(metric, "transport/foreign_host", "bgpForeignHost")
  return metric
'''

[[processors.starlark]]
  order = 1
  namepass = ["xe_environment_sensor*"]
  source = '''
def tag_from_field(metric, source, target):
  value = metric.fields.get(source)
  if value != None:
    metric.tags[target] = str(value)

def apply(metric):
  tag_from_field(metric, "sensor_name", "envSensorType")
  tag_from_field(metric, "sensor_units", "envSensorUnits")
  tag_from_field(metric, "state", "envSensorState")
  return metric
'''

[[processors.template]]
  order = 2
  namepass = ["xe_bgp_neighbors"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_{{ .Tag "bgpAfiSafi" }}_{{ .Tag "bgpVrfName" }}_{{ .Tag "bgpNeighborId" }}'

[[processors.template]]
  order = 2
  namepass = ["xe_bgp_neighbors"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_{{ .Tag "bgpVrfName" }}_{{ .Tag "bgpNeighborId" }}'

[[processors.template]]
  order = 3
  namepass = ["xe_bgp_neighbors*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-bgp-neighbor'

[[processors.template]]
  order = 4
  namepass = ["xe_bgp_neighbors*"]
  tag = "direction"
  template = '-1'

[[processors.template]]
  order = 2
  namepass = ["xe_environment_sensor"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_{{ .Tag "name" }}_{{ .Tag "location" }}'

[[processors.template]]
  order = 2
  namepass = ["xe_environment_sensor"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_{{ .Tag "name" }}_{{ .Tag "location" }}'

[[processors.template]]
  order = 3
  namepass = ["xe_environment_sensor*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-environment-sensor'

[[processors.template]]
  order = 4
  namepass = ["xe_environment_sensor*"]
  tag = "direction"
  template = '-1'

[[outputs.file]]
  files = ["/output/metrics.influx"]
  data_format = "influx"
  influx_sort_fields = true

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
  influx_sort_fields = true
