# Template Section for constructing object ID for interface objects
[[processors.template]]
  namepass = ["if_stats*"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_{{ .Tag "interface_name" }}'

[[processors.template]]
  namepass = ["if_stats*"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_{{ .Tag "interface_name" }}'

[[processors.template]]
  namepass = ["if_stats*"]
  tag = "objectType"
  template = 'cisco-telemetry-xr-interface'

[[processors.template]]
  namepass = ["if_stats*"]
  tag = "direction"
  template = "-1"

# Template Section for conditional and mathematical logic based metrics for Interface Objects
[[processors.starlark]]
  namepass = ["if_stats*"]

source = '''
def apply(metric):
    if metric.fields.get("state") == "im-state-up":
        metric.fields["availability_percent"] = 100
    else:
        metric.fields["availability_percent"] = 0
    if metric.fields.get("interface_statistics/stats_type") == "basic":
        metric.fields["interface_statistics/basic_interface_stats/bytes_received_rate"] = metric.fields.get("interface_statistics/basic_interface_stats/bytes_received")
        metric.fields["interface_statistics/basic_interface_stats/bytes_received_delta"] = metric.fields.get("interface_statistics/basic_interface_stats/bytes_received")
        metric.fields["interface_statistics/basic_interface_stats/bytes_sent_rate"] = metric.fields.get("interface_statistics/basic_interface_stats/bytes_sent")
        metric.fields["interface_statistics/basic_interface_stats/bytes_sent_delta"] = metric.fields.get("interface_statistics/basic_interface_stats/bytes_sent")
    elif metric.fields.get("interface_statistics/stats_type") == "full":
        metric.fields["interface_statistics/full_interface_stats/bytes_received_rate"] = metric.fields.get("interface_statistics/full_interface_stats/bytes_received")
        metric.fields["interface_statistics/full_interface_stats/bytes_received_delta"] = metric.fields.get("interface_statistics/full_interface_stats/bytes_received")
        metric.fields["interface_statistics/full_interface_stats/bytes_sent_rate"] = metric.fields.get("interface_statistics/full_interface_stats/bytes_sent")
        metric.fields["interface_statistics/full_interface_stats/bytes_sent_delta"] = metric.fields.get("interface_statistics/full_interface_stats/bytes_sent")
    return metric
'''

# Template Section for Renaming of metrics from source names and merging metric names for cases of one or the other metrics.
[[processors.rename]]
  namepass = ["if_stats*"]

  [[processors.rename.replace]]
    field = "interface_statistics/basic_interface_stats/input_errors"
    dest = "interface_statistics/full_interface_stats/input_errors"

  [[processors.rename.replace]]
    field = "interface_statistics/basic_interface_stats/output_errors"
    dest = "interface_statistics/full_interface_stats/output_errors"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/packets_received"
    dest = "interface_statistics/full_interface_stats/packets_received"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/packets_sent"
    dest = "interface_statistics/full_interface_stats/packets_sent"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/input_drops"
    dest = "interface_statistics/full_interface_stats/input_drops"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/output_drops"
    dest = "interface_statistics/full_interface_stats/output_drops"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/bytes_received_rate"
    dest = "interface_statistics/full_interface_stats/bytes_received_rate"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/bytes_received_delta"
    dest = "interface_statistics/full_interface_stats/bytes_received_delta"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/bytes_sent"
    dest = "interface_statistics/full_interface_stats/bytes_sent"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/bytes_sent_rate"
    dest = "interface_statistics/full_interface_stats/bytes_sent_rate"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/bytes_sent_delta"
    dest = "interface_statistics/full_interface_stats/bytes_sent_delta"

  [[processors.rename.replace]]
    field =  "interface_statistics/basic_interface_stats/bytes_received"
    dest = "interface_statistics/full_interface_stats/bytes_received"

# Template Section for specifying Fields to output from processor layer and tags for interface objects
[[processors.tag_limit]]
  namepass = ["if_stats*"]
  fieldinclude = [
    "state",
    "bandwidth",
    "data_rates/bandwidth",
    "data_rates/input_data_rate",
    "data_rates/output_data_rate",
    "interface_statistics/full_interface_stats/input_errors",
    "interface_statistics/full_interface_stats/output_errors",
    "interface_statistics/full_interface_stats/crc_errors",
    "interface_statistics/full_interface_stats/runt_packets_received",
    "interface_statistics/full_interface_stats/bytes_received",
    "interface_statistics/full_interface_stats/packets_received",
    "interface_statistics/full_interface_stats/packets_sent",
    "interface_statistics/full_interface_stats/input_drops",
    "interface_statistics/full_interface_stats/output_drops",
    "interface_statistics/full_interface_stats/bytes_received_rate",
    "interface_statistics/full_interface_stats/bytes_received_delta",
    "interface_statistics/full_interface_stats/bytes_sent",
    "interface_statistics/full_interface_stats/bytes_sent_rate",
    "interface_statistics/full_interface_stats/bytes_sent_delta",
    "availability_percent",
  ]
  ## Maximum number of tags to preserve
  limit = 4

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType","direction"]