# XE BGP Neighbor Stats

[[processors.starlark]]
order = 1
namepass = ["xe_bgp_neighbors*"]
source = '''
def tag_from_tag(metric, source, target):
  value = metric.tags.get(source)
  if value != None:
    metric.tags[target] = str(value)

def tag_from_field(metric, source, target):
  value = metric.fields.get(source)
  if value != None:
    metric.tags[target] = str(value)

def apply(metric):
  tag_from_tag(metric, "afi_safi", "bgpAfiSafi")
  tag_from_tag(metric, "vrf_name", "bgpVrfName")
  tag_from_tag(metric, "neighbor_id", "bgpNeighborId")
  tag_from_field(metric, "as", "bgpNeighborAs")
  tag_from_field(metric, "link", "bgpLink")
  tag_from_field(metric, "description", "bgpDescription")
  tag_from_field(metric, "session_state", "bgpSessionState")
  tag_from_field(metric, "connection/state", "bgpConnectionState")
  tag_from_field(metric, "connection/reset_reason", "bgpResetReason")
  tag_from_field(metric, "transport/local_host", "bgpLocalHost")
  tag_from_field(metric, "transport/foreign_host", "bgpForeignHost")
  if metric.tags.get("bgpDescription") == None:
    metric.tags["bgpDescription"] = metric.tags.get("bgpNeighborId")
  return metric
'''

[[processors.template]]
order = 2
  namepass = ["xe_bgp_neighbors"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_{{ .Tag "bgpAfiSafi" }}_{{ .Tag "bgpVrfName" }}_{{ .Tag "bgpNeighborId" }}'

[[processors.template]]
order = 2
  namepass = ["xe_bgp_neighbors"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_{{ .Tag "bgpAfiSafi" }}_{{ .Tag "bgpVrfName" }}_{{ .Tag "bgpDescription" }}'

[[processors.template]]
order = 3
  namepass = ["xe_bgp_neighbors*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-bgp-neighbor'

[[processors.template]]
order = 4
  namepass = ["xe_bgp_neighbors*"]
  tag = "direction"
  template = '-1'

[[processors.tag_limit]]
order = 5
  namepass = ["xe_bgp_neighbors*"]
  fieldinclude = [
        "bgp_version",
        "installed_prefixes",
        "negotiated_keepalive_timers/hold_time",
        "negotiated_keepalive_timers/keepalive_interval",
        "bgp_neighbor_counters/sent/opens",
        "bgp_neighbor_counters/sent/updates",
        "bgp_neighbor_counters/sent/notifications",
        "bgp_neighbor_counters/sent/keepalives",
        "bgp_neighbor_counters/sent/route_refreshes",
        "bgp_neighbor_counters/received/opens",
        "bgp_neighbor_counters/received/updates",
        "bgp_neighbor_counters/received/notifications",
        "bgp_neighbor_counters/received/keepalives",
        "bgp_neighbor_counters/received/route_refreshes",
        "bgp_neighbor_counters/inq_depth",
        "bgp_neighbor_counters/outq_depth",
        "connection/total_established",
        "connection/total_dropped",
        "transport/local_port",
        "transport/foreign_port",
        "transport/mss",
        "prefix_activity/sent/current_prefixes",
        "prefix_activity/sent/total_prefixes",
        "prefix_activity/sent/implicit_withdraw",
        "prefix_activity/sent/explicit_withdraw",
        "prefix_activity/sent/bestpaths",
        "prefix_activity/sent/multipaths",
        "prefix_activity/received/current_prefixes",
        "prefix_activity/received/total_prefixes",
        "prefix_activity/received/implicit_withdraw",
        "prefix_activity/received/explicit_withdraw",
        "prefix_activity/received/bestpaths",
        "prefix_activity/received/multipaths"
]

  ## Maximum number of tags to preserve
  limit = 16

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType", "direction", "source", "bgpAfiSafi", "bgpVrfName", "bgpNeighborId", "bgpNeighborAs", "bgpLink", "bgpDescription", "bgpSessionState", "bgpConnectionState", "bgpResetReason", "bgpLocalHost", "bgpForeignHost"]
