# XE Environment Sensor Stats

[[processors.starlark]]
order = 1
namepass = ["xe_environment_sensor*"]
source = '''
def sanitize(value):
  value = str(value)
  for char in [": ", ":", " ", "/", "-", "."]:
    value = value.replace(char, "_")
  for _ in range(8):
    value = value.replace("__", "_")
  return value

def apply(metric):
  sensor_name = metric.tags.get("name")
  location = metric.tags.get("location")
  reading = metric.fields.get("current_reading")

  for field in metric.fields.keys():
    metric.fields.pop(field)

  if sensor_name != None and location != None and reading != None:
    metric_name = sanitize(sensor_name) + "_" + sanitize(location)
    metric.fields[metric_name] = reading
  return metric
'''

[[processors.template]]
order = 2
  namepass = ["xe_environment_sensor"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_xe-environment-sensor'

[[processors.template]]
order = 2
  namepass = ["xe_environment_sensor"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_xe-environment-sensor'

[[processors.template]]
order = 3
  namepass = ["xe_environment_sensor*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-environment-sensor'

[[processors.template]]
order = 4
  namepass = ["xe_environment_sensor*"]
  tag = "direction"
  template = '-1'

[[processors.tag_limit]]
order = 5
  namepass = ["xe_environment_sensor*"]

  ## Maximum number of tags to preserve
  limit = 12

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType", "direction", "source"]
