# XE Environment Sensor Stats

[[processors.starlark]]
order = 1
namepass = ["xe_environment_sensor*"]
source = '''
def sanitize(value):
  value = str(value)
  for char in [": ", ":", " ", "/", "-", "."]:
    value = value.replace(char, "_")
  for _ in range(8):
    value = value.replace("__", "_")
  return value

def apply(metric):
  sensor_name = metric.tags.get("name")
  location = metric.tags.get("location")
  reading = metric.fields.get("current_reading")

  for field in metric.fields.keys():
    metric.fields.pop(field)

  if sensor_name != None and location != None and reading != None:
    metric_name = sanitize(sensor_name) + "_" + sanitize(location)
    metric.fields[metric_name] = reading
  return metric
'''

[[processors.template]]
order = 2
  namepass = ["xe_environment_sensor"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_xe-environment-sensor'

[[processors.template]]
order = 2
  namepass = ["xe_environment_sensor"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_xe-environment-sensor'

[[processors.template]]
order = 3
  namepass = ["xe_environment_sensor*"]
  tag = "objectType"
  template = 'cisco-telemetry-xe-environment-sensor'

[[processors.template]]
order = 4
  namepass = ["xe_environment_sensor*"]
  tag = "direction"
  template = '-1'

[[processors.tag_limit]]
order = 5
  namepass = ["xe_environment_sensor*"]
  fieldinclude = [
        "HotSwap_Power_R0",
        "HotSwap_Volts_R0",
        "Temp_InltFrnt_1_0",
        "Temp_InltFrnt_2_0",
        "Temp_InltFrnt_R0",
        "Temp_InltRear_1_0",
        "Temp_InltRear_2_0",
        "Temp_InltRear_R0",
        "Temp_OtltFrnt_1_0",
        "Temp_OtltFrnt_2_0",
        "Temp_OtltFrnt_R0",
        "Temp_OtltRear_1_0",
        "Temp_OtltRear_2_0",
        "Temp_OtltRear_R0",
        "Temp_UADP_0_0_R0",
        "Temp_UADP_0_1_R0",
        "Temp_UADP_0_2_R0",
        "Temp_UADP_0_3_R0",
        "Temp_UADP_0_4_R0",
        "Temp_UADP_0_5_R0",
        "Temp_UADP_0_6_R0",
        "Temp_UADP_0_7_R0",
        "Temp_UADP_0_8_R0",
        "Temp_UADP_1_0_R0",
        "Temp_UADP_1_1_R0",
        "Temp_UADP_1_2_R0",
        "Temp_UADP_1_3_R0",
        "Temp_UADP_1_4_R0",
        "Temp_UADP_1_5_R0",
        "Temp_UADP_1_6_R0",
        "Temp_UADP_1_7_R0",
        "Temp_UADP_1_8_R0",
        "Temp_UADP_2_0_R0",
        "Temp_UADP_2_1_R0",
        "Temp_UADP_2_2_R0",
        "Temp_UADP_2_3_R0",
        "Temp_UADP_2_4_R0",
        "Temp_UADP_2_5_R0",
        "Temp_UADP_2_6_R0",
        "Temp_UADP_2_7_R0",
        "Temp_UADP_2_8_R0"
]

  ## Maximum number of tags to preserve
  limit = 12

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType", "direction", "source"]
