# Template Section for constructing object ID for ipsla metrics
[[processors.template]]
namepass = ["ipsla*"]
tag = "sessionName"
template = '{{ .Tag "source" }}_ipsla_{{ .Tag "operation_id" }}'

[[processors.template]]
namepass = ["ipsla*"]
tag = "sessionId"
template = '{{ .Tag "source" }}_ipsla_{{ .Tag "operation_id" }}'

[[processors.template]]
namepass = ["ipsla*"]
tag = "objectType"
template = 'cisco-telemetry-xr-ipsla'

[[processors.template]]
namepass = ["ipsla*"]
tag = "direction"
template = '-1'

[[processors.tag_limit]]
  namepass = ["ipsla*"]
  fieldinclude = [
      "common_stats/response_time",
      "common_stats/min_response_time",
      "common_stats/max_response_time",
      "common_stats/response-time-count",
      "specific_stats/udp_jitter_stats/jitter_in",
      "specific_stats/udp_jitter_stats/jitter_out",
      "specific_stats/udp_jitter_stats/packet_loss_sd",
      "specific_stats/udp_jitter_stats/packet_loss_ds",
      "specific_stats/udp_jitter_stats/packet-late-arrivals",
      "specific_stats/udp_jitter_stats/packet-mia",
      "specific_stats/udp_jitter_stats/packet-out-of-sequence",
      "specific_stats/udp_jitter_stats/packet-skipped",
      "specific_stats/udp_jitter_stats/negative_ds_max",
      "specific_stats/udp_jitter_stats/negative_ds_min",
      "specific_stats/udp_jitter_stats/negative_sd_max",
      "specific_stats/udp_jitter_stats/negative_sd_min",
      "specific_stats/udp_jitter_stats/one_way_ds_max",
      "specific_stats/udp_jitter_stats/one_way_ds_min",
      "specific_stats/udp_jitter_stats/one_way_sd_max",
      "specific_stats/udp_jitter_stats/one_way_sd_min",
      "specific_stats/udp_jitter_stats/positive_ds_max",
      "specific_stats/udp_jitter_stats/positive_ds_min",
      "specific_stats/udp_jitter_stats/positive_sd_max",
      "specific_stats/udp_jitter_stats/positive_sd_min",
      "specific_stats/udp_jitter_stats/negative-sd-sum",
      "specific_stats/udp_jitter_stats/negative-ds-sum",
      "specific_stats/udp_jitter_stats/negative-sd-count",
      "specific_stats/udp_jitter_stats/positive-sd-sum",
      "specific_stats/udp_jitter_stats/positive-ds-sum",
      "specific_stats/udp_jitter_stats/positive-sd-count"
  ]
  ## Maximum number of tags to preserve
  limit = 4

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType","direction"]
