# Template Section for constructing object ID for node environmentals
[[processors.template]]
  namepass = ["cpu_util*", "node_summary*"]
  tag = "sessionName"
  template = '{{ .Tag "source" }}_{{ .Tag "node_name" }}'

[[processors.template]]
  namepass = ["cpu_util*", "node_summary*"]
  tag = "sessionId"
  template = '{{ .Tag "source" }}_{{ .Tag "node_name" }}'

[[processors.template]]
  namepass = ["cpu_util*", "node_summary*"]
  tag = "objectType"
  template = 'cisco-telemetry-xr-environment'

[[processors.template]]
  namepass = ["cpu_util*", "node_summary*"]
  tag = "direction"
  template = '-1'

# Template Section for specifying Fields to output from processor layer and tags for environment objects
[[processors.tag_limit]]
  namepass = ["cpu_util*", "node_summary*"]
  fieldinclude = [
    "total_cpu_five_minute",
    "ram_memory",
    "free_application_memory"
  ]
  ## Maximum number of tags to preserve
  limit = 4

  ## List of tags to preferentially preserve
  keep = ["sessionId", "sessionName", "objectType","direction"]

