# [[outputs.file]]
#   ## Files to write to, "stdout" is a specially handled file.
#   files = ["stdout"]
#   data_format = "prometheus"

[[inputs.execd]]
  command = ["python3", "/tmp/starlink_telemetry.py"]
  signal = "STDIN"
  data_format = "json_v2"

  [[inputs.execd.json_v2]]
    measurement_name = "starlink_telemetry_api"

    [[inputs.execd.json_v2.object]]
      path = "@this"
      timestamp_key = "UtcTimestampNs"
      timestamp_format = "unix_ns"
      disable_prepend_keys = true
      excluded_keys = ["ActiveAlerts"]
      tags = [
        "H3CellId",
        "DeviceType",
        "DeviceId",
        "RunningSoftwareVersion"
      ]
      [[inputs.execd.json_v2.object.field]]
        path = "#.DownlinkThroughput"
      [[inputs.execd.json_v2.object.field]]
        path = "#.UplinkThroughput"
      [[inputs.execd.json_v2.object.field]]
        path = "#.PingDropRateAvg"
      [[inputs.execd.json_v2.object.field]]
        path = "#.PingLatencyMsAvg"
      [[inputs.execd.json_v2.object.field]]
        path = "#.ObstructionPercentTime"
      [[inputs.execd.json_v2.object.field]]
        path = "#.Uptime"
      [[inputs.execd.json_v2.object.field]]
        path = "#.SignalQuality"
      [[inputs.execd.json_v2.object.field]]
        path = "#.SecondsUntilSwupdateRebootPossible"

  [[processors.template]]
    order = 2
    namepass = ["starlink_telemetry_api*"]
    tag = "direction"
    template = "2"
  [[processors.template]]
    order = 2
    namepass = ["starlink_telemetry_api*"]
    tag = "objectType"
    template = "Starlink-Telemetry-API"
  [[processors.template]]
    order = 2
    namepass = ["starlink_telemetry_api*"]
    tag = "sessionName"
    template = '{{ .Tag "DeviceType" }}_{{ .Tag "DeviceId" }}_Starlink-Telemetry-API'
  [[processors.template]]
    order = 2
    namepass = ["starlink_telemetry_api*"]
    tag = "sessionId"
    template = '{{ .Tag "DeviceType" }}_{{ .Tag "DeviceId" }}_Starlink-Telemetry-API'
  [[processors.template]]
    order = 2
    namepass = ["starlink_telemetry_api*"]
    tag = "name"
    template = '{{ .Tag "DeviceType" }}_{{ .Tag "DeviceId" }}_Starlink-Telemetry-API'
  [[processors.template]]
    order = 2
    namepass = ["starlink_telemetry_api*"]
    tag = "objectId"
    template = '{{ .Tag "DeviceType" }}_{{ .Tag "DeviceId" }}_Starlink-Telemetry-API'
