[agent]
  interval = "60s"
  flush_interval = "50s"
  # debug = true
  quiet = false

[[inputs.jti_openconfig_telemetry]]
    servers = ["192.168.21.33:32767"]
    sample_frequency = "60000ms"
    username = "__DEVICE_USERNAME__"
    password = "__DEVICE_PASSWORD__"
    client_id = "cisco-pca"
    sensors = [
    "/junos/system/linecard/cpu/memory",
    "/junos/system/linecard/interface/",
    "/junos/system/linecard/environment",
    ]
    collection_jitter = "0s"
    flush_interval = "15s"
    flush_jitter = "0s"

# ============================================================================
# RENAME METRICS FOR CLARITY
# ============================================================================
# Rename interface metrics

[[outputs.file]]
  files = ["/capture/collector-ingress.jsonl"]
  data_format = "json"
